#!/bin/sh . "$(dirname "$0")/\_/husky.sh"

# Proper commit message format is required for automated changelog generation. Examples:

# [<emoji>] [revert: ?]<type>[(scope)?]: <message>

# 💥 feat(compiler): add 'comments' option

# 🐛 fix(compiler): fix some bug

# 📝 docs(compiler): add some docs

# 🌷 UI(compiler): better styles

# 🏰 chore(compiler): Made some changes to the scaffolding

# 🌐 locale(compiler): Made a small contribution to internationalization

# Other commit types: refactor, perf, workflow, build, CI, typos, tests, types, wip, release, dep

# See https://github.com/vuejs/core/blob/main/.github/commit-convention.md

# 暂时关闭提交规范

# Export Git hook params

# export GIT_PARAMS=$\*

# npx --no-install fabric verify-commit

npx --no-install lint-staged --quiet
